# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('fec', ['core'])
    module.source = [
        'model/fec-agent.cc',
        'model/fec-router-agent.cc',
        'model/fec-tag.cc',
        'model/ipv4-l3-protocol-with-fec-encode.cc',
        'model/ipv4-l3-protocol-with-fec-decode.cc',
        'helper/fec-agent-container.cc',
        'helper/fec-router-agent-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('fec')
    module_test.source = [
        'test/fec-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/fec-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'fec'
    headers.source = [
        'model/fec-agent.h',
        'model/fec-router-agent.h',
        'model/fec-tag.h',
        'model/ipv4-l3-protocol-with-fec-encode.h',
        'model/ipv4-l3-protocol-with-fec-decode.h',
        'helper/fec-agent-container.h',
        'helper/fec-router-agent-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

